{% set name = "banks" %}
{% set version = "2.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/banks-{{ version }}.tar.gz
  sha256: 8cbf1553f14c44d4f7e9c2064ad9212ce53ee4da000b2f8308d548b60db56655

build:
  skip: true # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - filetype >=1.2.0
    - python
    - griffe
    - jinja2
    - pydantic
    - deprecated
    - platformdirs

test:
  imports:
    - banks
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/masci/banks
  summary: A prompt programming language
  description: |
    Banks is the linguist professor who will help you generate meaningful LLM
    prompts using a template language that makes sense.
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  doc_url: https://masci.github.io/banks/
  dev_url: https://github.com/masci/banks

extra:
  recipe-maintainers:
    - jan-janssen
