{% set name = "banks" %}
{% set version = "2.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a7ca5c250b605ae90cfd6e4ca5dd6ce2ee377d5d59021b6feba44e345910026d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - griffe
    - jinja2
    - pydantic
    - deprecated
    - eval-type-backport  # [py<310]
    - typing-extensions  # [py<311]
    - platformdirs
    - filetype >=1.2.0

# Tests disabled for the moment because no `distutils` available
# E   ModuleNotFoundError: No module named 'distutils'
test:
  imports:
    - banks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/masci/banks
  summary: A prompt programming language
  description: |
    Banks is the linguist professor who will help you generate meaningful LLM
    prompts using a template language that makes sense.
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  doc_url: https://masci.github.io/banks
  dev_url: https://github.com/masci/banks

extra:
  recipe-maintainers:
    - jan-janssen
