{% set name = "banks" %}
{% set version = "2.4.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff575732fc67d5493a73c21e0d7268bc49e86fff02b0b8735e8efb9fcb9af3a4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - griffe
    - jinja2
    - pydantic
    - eval-type-backport  # [py<310]
    - platformdirs
    - filetype >=1.2.0

test:
  imports:
    - banks
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/masci/banks
  summary: A prompt programming language
  description: |
    Banks is the linguist professor who will help you generate meaningful LLM
    prompts using a template language that makes sense.
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  doc_url: https://masci.github.io/banks/
  dev_url: https://github.com/masci/banks

extra:
  recipe-maintainers:
    - jan-janssen
